# Generated by Django 5.2.9 on 2026-01-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_navigation", "0002_alter_footernavigation_social_facebook_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="headernavigation",
            name="mobile_cta_label",
            field=models.CharField(
                blank=True,
                help_text="Optional label text shown in the mobile CTA bar (desktop view).",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="headernavigation",
            name="mobile_cta_label_compact",
            field=models.CharField(
                blank=True,
                help_text="Optional short label for the mobile CTA bar (small screens).",
                max_length=40,
            ),
        ),
    ]
