# Generated by Django 5.2.9 on 2026-01-19 10:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sum_core_navigation", "0004_alter_footernavigation_link_sections_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footernavigation",
            name="link_sections",
            field=wagtail.fields.StreamField(
                [("section", 12)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Section title (max 50 characters).",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("url", "External URL"),
                                ("path", "Internal path"),
                                ("email", "Email"),
                                ("phone", "Phone"),
                                ("anchor", "Anchor"),
                            ],
                            "help_text": "Select the type of link.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select an internal page.", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter an external URL (include https://).",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter an internal path starting with / (e.g., /portfolio/?type=bootroom).",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Enter an email address.", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter a phone number (e.g., +44 20 7946 0958).",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter an anchor ID (e.g., 'contact' or '#contact').",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Custom display text for the link (optional).",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": None,
                            "help_text": "Force link to open in new tab. External URLs open in new tab by default.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 1),
                                ("page", 2),
                                ("url", 3),
                                ("path", 4),
                                ("email", 5),
                                ("phone", 6),
                                ("anchor", 7),
                                ("link_text", 8),
                                ("open_in_new_tab", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {
                            "help_text": "Links in this section (max 10 links).",
                            "max_num": 10,
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("links", 11)]],
                        {},
                    ),
                },
                help_text="Footer link sections (min 2, max 4 sections).",
            ),
        ),
        migrations.AlterField(
            model_name="headernavigation",
            name="header_cta_link",
            field=wagtail.fields.StreamField(
                [("link", 9)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("url", "External URL"),
                                ("path", "Internal path"),
                                ("email", "Email"),
                                ("phone", "Phone"),
                                ("anchor", "Anchor"),
                            ],
                            "help_text": "Select the type of link.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select an internal page.", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter an external URL (include https://).",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter an internal path starting with / (e.g., /portfolio/?type=bootroom).",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Enter an email address.", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter a phone number (e.g., +44 20 7946 0958).",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter an anchor ID (e.g., 'contact' or '#contact').",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Custom display text for the link (optional).",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": None,
                            "help_text": "Force link to open in new tab. External URLs open in new tab by default.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 0),
                                ("page", 1),
                                ("url", 2),
                                ("path", 3),
                                ("email", 4),
                                ("phone", 5),
                                ("anchor", 6),
                                ("link_text", 7),
                                ("open_in_new_tab", 8),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Link destination for header CTA (optional, max 1).",
            ),
        ),
        migrations.AlterField(
            model_name="headernavigation",
            name="menu_items",
            field=wagtail.fields.StreamField(
                [("item", 15)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Menu item label (max 50 characters).",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("url", "External URL"),
                                ("path", "Internal path"),
                                ("email", "Email"),
                                ("phone", "Phone"),
                                ("anchor", "Anchor"),
                            ],
                            "help_text": "Select the type of link.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select an internal page.", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter an external URL (include https://).",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter an internal path starting with / (e.g., /portfolio/?type=bootroom).",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Enter an email address.", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter a phone number (e.g., +44 20 7946 0958).",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter an anchor ID (e.g., 'contact' or '#contact').",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Custom display text for the link (optional).",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": None,
                            "help_text": "Force link to open in new tab. External URLs open in new tab by default.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 1),
                                ("page", 2),
                                ("url", 3),
                                ("path", 4),
                                ("email", 5),
                                ("phone", 6),
                                ("anchor", 7),
                                ("link_text", 8),
                                ("open_in_new_tab", 9),
                            ]
                        ],
                        {
                            "help_text": "Link destination for this menu item.",
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("link", 10)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.ListBlock",
                        (11,),
                        {
                            "help_text": "Nested menu items (optional, max 8 items).",
                            "max_num": 8,
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("link", 10), ("children", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.ListBlock",
                        (13,),
                        {
                            "help_text": "Submenu items (optional, max 8 items).",
                            "max_num": 8,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("link", 10), ("children", 14)]],
                        {},
                    ),
                },
                help_text="Top-level menu items (max 8).",
            ),
        ),
        migrations.AlterField(
            model_name="headernavigation",
            name="mobile_cta_button_link",
            field=wagtail.fields.StreamField(
                [("link", 9)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("url", "External URL"),
                                ("path", "Internal path"),
                                ("email", "Email"),
                                ("phone", "Phone"),
                                ("anchor", "Anchor"),
                            ],
                            "help_text": "Select the type of link.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select an internal page.", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter an external URL (include https://).",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter an internal path starting with / (e.g., /portfolio/?type=bootroom).",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Enter an email address.", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter a phone number (e.g., +44 20 7946 0958).",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter an anchor ID (e.g., 'contact' or '#contact').",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Custom display text for the link (optional).",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": None,
                            "help_text": "Force link to open in new tab. External URLs open in new tab by default.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 0),
                                ("page", 1),
                                ("url", 2),
                                ("path", 3),
                                ("email", 4),
                                ("phone", 5),
                                ("anchor", 6),
                                ("link_text", 7),
                                ("open_in_new_tab", 8),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Link destination for mobile CTA button (optional, max 1).",
            ),
        ),
    ]
