# Generated by Django 5.1.15 on 2026-01-19 13:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sum_core_navigation", "0005_alter_footernavigation_link_sections_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="headernavigation",
            name="desktop_sticky_cta_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable the desktop sticky CTA site-wide."
            ),
        ),
        migrations.CreateModel(
            name="DesktopStickyCTASnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Internal label for editors.", max_length=80
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional label shown alongside the button.",
                        max_length=80,
                    ),
                ),
                (
                    "compact_label",
                    models.CharField(
                        blank=True,
                        help_text="Optional compact label for tight layouts.",
                        max_length=40,
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True,
                        help_text="Button text (max 50 characters).",
                        max_length=50,
                    ),
                ),
                (
                    "button_link",
                    wagtail.fields.StreamField(
                        [("link", 9)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("page", "Page"),
                                        ("url", "External URL"),
                                        ("path", "Internal path"),
                                        ("email", "Email"),
                                        ("phone", "Phone"),
                                        ("anchor", "Anchor"),
                                    ],
                                    "help_text": "Select the type of link.",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Select an internal page.",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Enter an external URL (include https://).",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter an internal path starting with / (e.g., /portfolio/?type=bootroom).",
                                    "max_length": 500,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.EmailBlock",
                                (),
                                {
                                    "help_text": "Enter an email address.",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter a phone number (e.g., +44 20 7946 0958).",
                                    "max_length": 30,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter an anchor ID (e.g., 'contact' or '#contact').",
                                    "max_length": 100,
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Custom display text for the link (optional).",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": None,
                                    "help_text": "Force link to open in new tab. External URLs open in new tab by default.",
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("link_type", 0),
                                        ("page", 1),
                                        ("url", 2),
                                        ("path", 3),
                                        ("email", 4),
                                        ("phone", 5),
                                        ("anchor", 6),
                                        ("link_text", 7),
                                        ("open_in_new_tab", 8),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Link destination for the desktop sticky CTA button.",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional site restriction for this CTA snippet.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desktop_sticky_ctas",
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Desktop Sticky CTA",
                "verbose_name_plural": "Desktop Sticky CTAs",
            },
        ),
        migrations.AddField(
            model_name="headernavigation",
            name="desktop_sticky_cta_snippet",
            field=models.ForeignKey(
                blank=True,
                help_text="Desktop sticky CTA snippet to use by default.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sum_core_navigation.desktopstickyctasnippet",
            ),
        ),
    ]
