# Generated by Django 5.1.15 on 2026-01-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sum_core_navigation",
            "0006_headernavigation_desktop_sticky_cta_enabled_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="desktopstickyctasnippet",
            name="compact_label",
        ),
    ]
