# Generated by Django 5.2.10 on 2026-01-21 14:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sum_core_navigation", "0007_remove_desktopstickyctasnippet_compact_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="headernavigation",
            name="menu_items",
            field=wagtail.fields.StreamField(
                [("item", 20)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Menu item label (max 50 characters).",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("url", "External URL"),
                                ("path", "Internal path"),
                                ("email", "Email"),
                                ("phone", "Phone"),
                                ("anchor", "Anchor"),
                            ],
                            "help_text": "Select the type of link.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select an internal page.", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter an external URL (include https://).",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter an internal path starting with / (e.g., /portfolio/?type=bootroom).",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Enter an email address.", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter a phone number (e.g., +44 20 7946 0958).",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter an anchor ID (e.g., 'contact' or '#contact').",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Custom display text for the link (optional).",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": None,
                            "help_text": "Force link to open in new tab. External URLs open in new tab by default.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 1),
                                ("page", 2),
                                ("url", 3),
                                ("path", 4),
                                ("email", 5),
                                ("phone", 6),
                                ("anchor", 7),
                                ("link_text", 8),
                                ("open_in_new_tab", 9),
                            ]
                        ],
                        {
                            "help_text": "Link destination for this menu item.",
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("link", 10)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.ListBlock",
                        (11,),
                        {
                            "help_text": "Nested menu items (optional, max 8 items).",
                            "max_num": 8,
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("link", 10), ("children", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.ListBlock",
                        (13,),
                        {
                            "help_text": "Submenu items (optional, max 8 items).",
                            "max_num": 8,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Featured image for mega menu (displayed on desktop only).",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Label above the featured title (e.g., 'Featured').",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title for the featured item.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "CTA text for the featured item (e.g., 'Explore Case Study').",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 1),
                                ("page", 2),
                                ("url", 3),
                                ("path", 4),
                                ("email", 5),
                                ("phone", 6),
                                ("anchor", 7),
                                ("link_text", 8),
                                ("open_in_new_tab", 9),
                            ]
                        ],
                        {
                            "help_text": "Link destination for the featured item.",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 0),
                                ("link", 10),
                                ("children", 14),
                                ("featured_image", 15),
                                ("featured_label", 16),
                                ("featured_title", 17),
                                ("featured_link_text", 18),
                                ("featured_link", 19),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Top-level menu items (max 8).",
            ),
        ),
    ]
