# Generated by Django 5.2.10 on 2026-02-04 20:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrashCan",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trash",
                "verbose_name_plural": "Trash",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="TrashedPageInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_path",
                    models.CharField(
                        help_text="URL path before trashing.", max_length=255
                    ),
                ),
                (
                    "original_slug",
                    models.CharField(
                        help_text="Slug before modification for trash.", max_length=255
                    ),
                ),
                (
                    "trashed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the page was trashed.",
                    ),
                ),
                (
                    "descendant_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of descendant pages trashed with this page.",
                    ),
                ),
                (
                    "original_parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="The parent page before trashing (for restoration).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trashed_children",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "page",
                    models.OneToOneField(
                        help_text="The page that was trashed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trash_info",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "trashed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the trash operation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trashed_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trashed Page Info",
                "verbose_name_plural": "Trashed Page Info",
                "ordering": ["-trashed_at"],
                "indexes": [
                    models.Index(
                        fields=["trashed_at"], name="wagtail_tra_trashed_62b47a_idx"
                    ),
                    models.Index(
                        fields=["original_parent"],
                        name="wagtail_tra_origina_291148_idx",
                    ),
                ],
            },
        ),
    ]
