# Generated by Django 5.2.9 on 2026-01-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=200)),
                ("link_text", models.CharField(blank=True, max_length=50)),
                ("link_url", models.URLField(blank=True)),
                (
                    "background_color",
                    models.CharField(
                        choices=[
                            ("bg-sage-terra", "Terra"),
                            ("bg-sage-black", "Black"),
                            ("bg-sage-moss", "Moss"),
                        ],
                        default="bg-sage-terra",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("dismissible", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Alert Banner",
                "verbose_name_plural": "Alert Banners",
            },
        ),
    ]
