# Generated by Django 5.2.9 on 2026-01-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_banners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertbanner",
            name="dismissible",
            field=models.BooleanField(
                default=True, help_text="Allow users to dismiss this banner."
            ),
        ),
        migrations.AlterField(
            model_name="alertbanner",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Banner will not show after this date/time.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="alertbanner",
            name="start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Banner will not show before this date/time.",
                null=True,
            ),
        ),
    ]
