# Generated by Django 5.2.10 on 2026-01-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sum_core_banners", "0002_alter_alertbanner_dismissible_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertbanner",
            name="background_color",
            field=models.CharField(
                choices=[
                    ("bg-primary", "Primary"),
                    ("bg-secondary", "Secondary"),
                    ("bg-accent", "Accent"),
                ],
                default="bg-primary",
                max_length=20,
            ),
        ),
    ]
