# Generated by Django 5.2.9 on 2026-01-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_leads", "0006_lead_dynamic_form_status_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="email_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In progress"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("disabled", "Disabled"),
                ],
                default="pending",
                help_text="Status of email notification delivery.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="webhook_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In progress"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("disabled", "Disabled"),
                ],
                default="pending",
                help_text="Status of webhook notification delivery.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="zapier_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In progress"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("disabled", "Disabled"),
                ],
                default="pending",
                help_text="Status of Zapier webhook delivery.",
                max_length=20,
            ),
        ),
    ]
