# Generated by Django 5.2.10 on 2026-01-23 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sum_core_leads", "0009_lead_assigned_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Status Changed"),
                            ("assignment_change", "Assignment Changed"),
                            ("note_added", "Note Added"),
                            ("created", "Lead Created"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True,
                        help_text="Previous value (JSON for flexibility).",
                        null=True,
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True,
                        help_text="New value (JSON for flexibility).",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable description of the activity.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action (null for system actions).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="sum_core_leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Activity",
                "verbose_name_plural": "Lead Activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "-created_at"],
                        name="sum_core_le_lead_id_dc3232_idx",
                    )
                ],
            },
        ),
    ]
