# Generated by Django 5.2.10 on 2026-01-24 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sum_core_leads", "0010_leadactivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="leadnote",
            index=models.Index(
                fields=["lead", "-created_at"], name="sum_core_le_lead_id_ce3bb0_idx"
            ),
        ),
    ]
