# Generated by Django 5.2.10 on 2026-01-24 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sum_core_leads", "0011_leadnote_sum_core_le_lead_id_ce3bb0_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="score",
            field=models.IntegerField(
                db_index=True,
                default=0,
                help_text="Lead priority score (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="score_updated_at",
            field=models.DateTimeField(
                blank=True, help_text="When score was last calculated", null=True
            ),
        ),
    ]
