# Generated by Django 5.2.9 on 2026-01-13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "sum_core_pages",
            "0015_alter_blogpostpage_body_alter_legalpage_sections_and_more",
        ),
        (
            "sum_core_pages",
            "0016_alter_blogpostpage_body_alter_legalpage_sections_and_more",
        ),
    ]

    operations = []
