# Generated by Django 5.2.9 on 2026-01-17 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_pages", "0024_add_editorial_header_anchor"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPromoSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(blank=True, max_length=80)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                ("link_text", models.CharField(blank=True, max_length=80)),
                ("link_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional site restriction for this promo.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_promos",
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog promo",
                "verbose_name_plural": "Blog promos",
            },
        ),
    ]
