# Generated by Django 5.2.9 on 2026-01-17 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_pages", "0025_blogpromosnippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="featured_post",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional featured post pinned to the top of the listing.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sum_core_pages.blogpostpage",
            ),
        ),
    ]
