# Generated by Django 5.2.9 on 2026-01-17 17:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "sum_core_pages",
            "0028_alter_blogpostpage_body_alter_casestudypage_body_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("lead_paragraph", 1),
                    ("article_section", 10),
                    ("content", 12),
                    ("numbered_steps", 17),
                    ("quote", 21),
                    ("social_proof_quote", 24),
                    ("image_block", 29),
                    ("call_to_action", 37),
                    ("spacer", 39),
                    ("divider", 41),
                    ("dynamic_form", 46),
                    ("rich_text", 47),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Lead paragraph copy. Use italics to highlight opening phrases.",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 0)]],
                        {"group": "Blog"},
                    ),
                    2: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "help_text": "Optional anchor ID used for in-page links (lowercase letters, numbers, and hyphens only).",
                            "regex": "^[a-z][a-z0-9-]*$",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center")],
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional eyebrow label.", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["italic", "bold"],
                            "help_text": "Section heading. Use italics for accent styling.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional subheading line under the main heading.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional second subheading line.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Style the first paragraph with a drop cap.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                            ],
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor", 2),
                                ("align", 3),
                                ("eyebrow", 4),
                                ("heading", 5),
                                ("subheading", 6),
                                ("subheading_secondary", 7),
                                ("drop_cap", 8),
                                ("body", 9),
                            ]
                        ],
                        {"group": "Blog"},
                    ),
                    11: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                            ],
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("align", 3), ("body", 11)]],
                        {"group": "Blog"},
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    14: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 13), ("description", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ListBlock",
                        (15,),
                        {"max_num": 8, "min_num": 1},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("steps", 16)]],
                        {"group": "Blog"},
                    ),
                    18: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Short editorial quote (1-3 sentences).",
                            "label": "Quote Text",
                        },
                    ),
                    19: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Role/description, e.g. Property Owner",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 18), ("author", 19), ("role", 20)]],
                        {"group": "Blog"},
                    ),
                    22: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Editorial quote (1-3 sentences).",
                            "label": "Quote Text",
                        },
                    ),
                    23: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional company logo.", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 22),
                                ("logo", 23),
                                ("author", 19),
                                ("role", 19),
                                ("company", 19),
                            ]
                        ],
                        {"group": "Blog"},
                    ),
                    25: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Short caption under the image.",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch to full-width container.",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 25),
                                ("alt_text", 26),
                                ("caption", 27),
                                ("full_width", 28),
                            ]
                        ],
                        {"group": "Blog"},
                    ),
                    30: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["italic", "bold"],
                            "help_text": "CTA heading. Use italics for accent styling.",
                            "required": True,
                        },
                    ),
                    31: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Supporting CTA copy.",
                            "required": True,
                        },
                    ),
                    32: ("wagtail.blocks.CharBlock", (), {}),
                    33: ("wagtail.blocks.URLBlock", (), {}),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                            ]
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 32), ("url", 33), ("style", 34)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.ListBlock",
                        (35,),
                        {"max_num": 2, "min_num": 1},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("eyebrow", 4),
                                ("heading", 30),
                                ("body", 31),
                                ("buttons", 36),
                            ]
                        ],
                        {"group": "Blog"},
                    ),
                    38: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small (24px)"),
                                ("medium", "Medium (40px)"),
                                ("large", "Large (64px)"),
                                ("xlarge", "X-Large (96px)"),
                            ]
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("size", 38)]],
                        {"group": "Blog"},
                    ),
                    40: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("muted", "Muted"),
                                ("strong", "Strong"),
                                ("accent", "Accent"),
                            ]
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("style", 40)]],
                        {"group": "Blog"},
                    ),
                    42: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("sum_core_forms.FormDefinition",),
                        {"help_text": "Select the form to display", "required": True},
                    ),
                    43: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("inline", "Inline (renders in page flow)"),
                                ("modal", "Modal (button opens overlay)"),
                                ("sidebar", "Sidebar (fixed slide-in)"),
                            ],
                            "help_text": "How the form should be presented",
                        },
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Override default CTA button text (for modal/sidebar styles)",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional redirect after submission (defaults to same page with message)",
                            "required": False,
                        },
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("form_definition", 42),
                                ("presentation_style", 43),
                                ("cta_button_text", 44),
                                ("success_redirect_url", 45),
                            ]
                        ],
                        {"group": "Forms"},
                    ),
                    47: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                            ],
                            "help_text": "Add formatted text content. Use H2-H4 for headings, avoid H1.",
                            "label": "Rich Text",
                            "required": False,
                        },
                    ),
                },
                help_text="Article content with optional form CTAs",
            ),
        ),
    ]
