# Generated by Django 5.2.9 on 2026-01-17 19:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "sum_core_pages",
            "0030_alter_blogpostpage_body_alter_casestudypage_body_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="sidebar_subscribe",
            field=wagtail.fields.StreamField(
                [("lead_magnet", 8)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Small label above the heading (e.g. 'Free Resource').",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic"],
                            "help_text": "Lead magnet heading.",
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional supporting copy.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("sum_core_forms.FormDefinition",),
                        {
                            "help_text": "Optional dynamic form definition. If empty, render email-only.",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional email field label or placeholder.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional submit button label.",
                            "max_length": 80,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional success message after submission.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("inline", "Inline"), ("sidebar", "Sidebar")],
                            "help_text": "Layout variant for the lead magnet.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("eyebrow", 0),
                                ("heading", 1),
                                ("description", 2),
                                ("form_definition", 3),
                                ("email_label", 4),
                                ("submit_label", 5),
                                ("success_message", 6),
                                ("variant", 7),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Optional lead magnet shown in the blog article sidebar.",
            ),
        ),
    ]
