# Generated by Django 5.2.9 on 2026-01-17 22:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_pages", "0035_portfolio_hero_heading_richtext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioindexpage",
            name="hero_heading",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Hero heading copy; supports italic/bold/accent emphasis.",
            ),
        ),
    ]
