# Generated by Django 5.2.9 on 2026-01-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_pages", "0036_portfolio_hero_heading_accent"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceindexpage",
            name="show_service_grid",
            field=models.BooleanField(
                default=True,
                help_text="Show the automatic grid of child services below the intro.",
            ),
        ),
    ]
