# Generated by Django 5.2.9 on 2026-01-18 10:11

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_pages", "0038_alter_casestudypage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceindexpage",
            name="hero_gradient_style",
            field=models.CharField(
                choices=[
                    ("primary", "Primary gradient"),
                    ("secondary", "Secondary gradient"),
                    ("accent", "Accent gradient"),
                ],
                default="primary",
                help_text="Gradient theme for the hero background.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="serviceindexpage",
            name="hero_heading",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Main hero heading. Use Italic for accent emphasis.",
            ),
        ),
        migrations.AddField(
            model_name="serviceindexpage",
            name="hero_status",
            field=models.CharField(
                blank=True,
                help_text="Optional eyebrow/status line above the hero heading.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="serviceindexpage",
            name="hero_subheading",
            field=models.TextField(
                blank=True,
                help_text="Optional supporting copy shown alongside the hero heading.",
            ),
        ),
    ]
