# Generated by Django 5.2.9 on 2026-01-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sum_core_pages",
            "0040_alter_blogpostpage_body_alter_casestudypage_body_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogindexpage",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Optional. Overrides the search description for SEO snippets (recommended max 160 characters).",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Optional. Overrides the SEO title when set; otherwise uses the SEO title or “{page title} | {site name}”.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="blogpostpage",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Optional. Overrides the search description for SEO snippets (recommended max 160 characters).",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="blogpostpage",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Optional. Overrides the SEO title when set; otherwise uses the SEO title or “{page title} | {site name}”.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="casestudypage",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Optional. Overrides the search description for SEO snippets (recommended max 160 characters).",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="casestudypage",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Optional. Overrides the SEO title when set; otherwise uses the SEO title or “{page title} | {site name}”.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="legalpage",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Optional. Overrides the search description for SEO snippets (recommended max 160 characters).",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="legalpage",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Optional. Overrides the SEO title when set; otherwise uses the SEO title or “{page title} | {site name}”.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioindexpage",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Optional. Overrides the search description for SEO snippets (recommended max 160 characters).",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioindexpage",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Optional. Overrides the SEO title when set; otherwise uses the SEO title or “{page title} | {site name}”.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="serviceindexpage",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Optional. Overrides the search description for SEO snippets (recommended max 160 characters).",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="serviceindexpage",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Optional. Overrides the SEO title when set; otherwise uses the SEO title or “{page title} | {site name}”.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="servicepage",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Optional. Overrides the search description for SEO snippets (recommended max 160 characters).",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="servicepage",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Optional. Overrides the SEO title when set; otherwise uses the SEO title or “{page title} | {site name}”.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Optional. Overrides the search description for SEO snippets (recommended max 160 characters).",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Optional. Overrides the SEO title when set; otherwise uses the SEO title or “{page title} | {site name}”.",
                max_length=60,
            ),
        ),
    ]
