# Generated by Django 5.2.9 on 2026-01-18 17:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sum_core_pages",
            "0040_alter_blogpostpage_body_alter_casestudypage_body_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("editorial_header", 4),
                    ("lead_paragraph", 6),
                    ("article_section", 13),
                    ("content", 15),
                    ("numbered_steps", 20),
                    ("quote", 24),
                    ("social_proof_quote", 27),
                    ("image_block", 32),
                    ("call_to_action", 49),
                    ("spacer", 51),
                    ("divider", 53),
                    ("dynamic_form", 58),
                    ("rich_text", 59),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "help_text": "Optional anchor ID used for in-page links (lowercase letters, numbers, and hyphens only).",
                            "regex": "^[a-z][a-z0-9-]*$",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center")],
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "e.g. Case Study", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["italic", "bold"],
                            "help_text": "Main title. Use italics for accent styling.",
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("anchor", 0), ("align", 1), ("eyebrow", 2), ("heading", 3)]],
                        {"group": "Blog"},
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Lead paragraph copy. Use italics to highlight opening phrases.",
                            "required": True,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 5)]],
                        {"group": "Blog"},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional eyebrow label.", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["italic", "bold"],
                            "help_text": "Section heading. Use italics for accent styling.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional subheading line under the main heading.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional second subheading line.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Style the first paragraph with a drop cap.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                            ],
                            "required": True,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor", 0),
                                ("align", 1),
                                ("eyebrow", 7),
                                ("heading", 8),
                                ("subheading", 9),
                                ("subheading_secondary", 10),
                                ("drop_cap", 11),
                                ("body", 12),
                            ]
                        ],
                        {"group": "Blog"},
                    ),
                    14: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                            ],
                            "required": True,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("align", 1), ("body", 14)]],
                        {"group": "Blog"},
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    17: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 16), ("description", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.ListBlock",
                        (18,),
                        {"max_num": 8, "min_num": 1},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("steps", 19)]],
                        {"group": "Blog"},
                    ),
                    21: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Short editorial quote (1-3 sentences).",
                            "label": "Quote Text",
                        },
                    ),
                    22: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Role/description, e.g. Property Owner",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 21), ("author", 22), ("role", 23)]],
                        {"group": "Blog"},
                    ),
                    25: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Editorial quote (1-3 sentences).",
                            "label": "Quote Text",
                        },
                    ),
                    26: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional company logo.", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 25),
                                ("logo", 26),
                                ("author", 22),
                                ("role", 22),
                                ("company", 22),
                            ]
                        ],
                        {"group": "Blog"},
                    ),
                    28: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Short caption under the image.",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch to full-width container.",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 28),
                                ("alt_text", 29),
                                ("caption", 30),
                                ("full_width", 31),
                            ]
                        ],
                        {"group": "Blog"},
                    ),
                    33: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["italic", "bold"],
                            "help_text": "CTA heading. Use italics for accent styling.",
                            "required": True,
                        },
                    ),
                    34: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Supporting CTA copy.",
                            "required": True,
                        },
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "CTA label text.",
                            "max_length": 80,
                            "required": True,
                        },
                    ),
                    36: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("url", "External URL"),
                                ("path", "Internal path"),
                                ("email", "Email"),
                                ("phone", "Phone"),
                                ("anchor", "Anchor"),
                            ],
                            "help_text": "Select the type of link.",
                        },
                    ),
                    37: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select an internal page.", "required": False},
                    ),
                    38: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter an external URL (include https://).",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter an internal path starting with / (e.g., /portfolio/?type=bootroom).",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Enter an email address.", "required": False},
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter a phone number (e.g., +44 20 7946 0958).",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter an anchor ID (e.g., 'contact' or '#contact').",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Custom display text for the link (optional).",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": None,
                            "help_text": "Force link to open in new tab. External URLs open in new tab by default.",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 36),
                                ("page", 37),
                                ("url", 38),
                                ("path", 39),
                                ("email", 40),
                                ("phone", 41),
                                ("anchor", 42),
                                ("link_text", 43),
                                ("open_in_new_tab", 44),
                            ]
                        ],
                        {"help_text": "CTA destination.", "required": True},
                    ),
                    46: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                            ],
                            "help_text": "Optional CTA style.",
                            "required": False,
                        },
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 35), ("link", 45), ("style", 46)]],
                        {},
                    ),
                    48: (
                        "wagtail.blocks.ListBlock",
                        (47,),
                        {"max_num": 2, "min_num": 1},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("eyebrow", 7),
                                ("heading", 33),
                                ("body", 34),
                                ("buttons", 48),
                            ]
                        ],
                        {"group": "Blog"},
                    ),
                    50: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small (24px)"),
                                ("medium", "Medium (40px)"),
                                ("large", "Large (64px)"),
                                ("xlarge", "X-Large (96px)"),
                            ]
                        },
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("size", 50)]],
                        {"group": "Blog"},
                    ),
                    52: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("muted", "Muted"),
                                ("strong", "Strong"),
                                ("accent", "Accent"),
                            ]
                        },
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [[("style", 52)]],
                        {"group": "Blog"},
                    ),
                    54: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("sum_core_forms.FormDefinition",),
                        {"help_text": "Select the form to display", "required": True},
                    ),
                    55: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("inline", "Inline (renders in page flow)"),
                                ("modal", "Modal (button opens overlay)"),
                                ("sidebar", "Sidebar (fixed slide-in)"),
                            ],
                            "help_text": "How the form should be presented",
                        },
                    ),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Override default CTA button text (for modal/sidebar styles)",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    57: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional redirect after submission (defaults to same page with message)",
                            "required": False,
                        },
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("form_definition", 54),
                                ("presentation_style", 55),
                                ("cta_button_text", 56),
                                ("success_redirect_url", 57),
                            ]
                        ],
                        {"group": "Forms"},
                    ),
                    59: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                            ],
                            "help_text": "Add formatted text content. Use H2-H4 for headings, avoid H1.",
                            "label": "Rich Text",
                            "required": False,
                        },
                    ),
                },
                help_text="Article content with optional form CTAs",
            ),
        ),
    ]
