# Generated by Django 5.2.9 on 2026-01-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sum_core_pages", "0050_alter_casestudypage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardpage",
            name="hero_intro",
            field=models.TextField(
                blank=True,
                help_text="Optional intro text displayed in the hero area.",
            ),
        ),
    ]
