# Generated by Django 5.1.15 on 2026-01-19 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sum_core_navigation",
            "0006_headernavigation_desktop_sticky_cta_enabled_and_more",
        ),
        ("sum_core_pages", "0050_alter_casestudypage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="desktop_sticky_cta_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit site default"),
                    ("disabled", "Disabled"),
                    ("custom", "Custom snippet"),
                ],
                default="inherit",
                help_text="Control whether this page uses the site default or a custom CTA.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="desktop_sticky_cta_snippet",
            field=models.ForeignKey(
                blank=True,
                help_text="Used when mode is set to Custom snippet.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sum_core_navigation.desktopstickyctasnippet",
            ),
        ),
        migrations.AddField(
            model_name="blogpostpage",
            name="desktop_sticky_cta_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit site default"),
                    ("disabled", "Disabled"),
                    ("custom", "Custom snippet"),
                ],
                default="inherit",
                help_text="Control whether this page uses the site default or a custom CTA.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="blogpostpage",
            name="desktop_sticky_cta_snippet",
            field=models.ForeignKey(
                blank=True,
                help_text="Used when mode is set to Custom snippet.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sum_core_navigation.desktopstickyctasnippet",
            ),
        ),
        migrations.AddField(
            model_name="casestudypage",
            name="desktop_sticky_cta_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit site default"),
                    ("disabled", "Disabled"),
                    ("custom", "Custom snippet"),
                ],
                default="inherit",
                help_text="Control whether this page uses the site default or a custom CTA.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="casestudypage",
            name="desktop_sticky_cta_snippet",
            field=models.ForeignKey(
                blank=True,
                help_text="Used when mode is set to Custom snippet.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sum_core_navigation.desktopstickyctasnippet",
            ),
        ),
        migrations.AddField(
            model_name="legalpage",
            name="desktop_sticky_cta_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit site default"),
                    ("disabled", "Disabled"),
                    ("custom", "Custom snippet"),
                ],
                default="inherit",
                help_text="Control whether this page uses the site default or a custom CTA.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="legalpage",
            name="desktop_sticky_cta_snippet",
            field=models.ForeignKey(
                blank=True,
                help_text="Used when mode is set to Custom snippet.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sum_core_navigation.desktopstickyctasnippet",
            ),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="desktop_sticky_cta_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit site default"),
                    ("disabled", "Disabled"),
                    ("custom", "Custom snippet"),
                ],
                default="inherit",
                help_text="Control whether this page uses the site default or a custom CTA.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="desktop_sticky_cta_snippet",
            field=models.ForeignKey(
                blank=True,
                help_text="Used when mode is set to Custom snippet.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sum_core_navigation.desktopstickyctasnippet",
            ),
        ),
        migrations.AddField(
            model_name="serviceindexpage",
            name="desktop_sticky_cta_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit site default"),
                    ("disabled", "Disabled"),
                    ("custom", "Custom snippet"),
                ],
                default="inherit",
                help_text="Control whether this page uses the site default or a custom CTA.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="serviceindexpage",
            name="desktop_sticky_cta_snippet",
            field=models.ForeignKey(
                blank=True,
                help_text="Used when mode is set to Custom snippet.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sum_core_navigation.desktopstickyctasnippet",
            ),
        ),
        migrations.AddField(
            model_name="servicepage",
            name="desktop_sticky_cta_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit site default"),
                    ("disabled", "Disabled"),
                    ("custom", "Custom snippet"),
                ],
                default="inherit",
                help_text="Control whether this page uses the site default or a custom CTA.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="servicepage",
            name="desktop_sticky_cta_snippet",
            field=models.ForeignKey(
                blank=True,
                help_text="Used when mode is set to Custom snippet.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sum_core_navigation.desktopstickyctasnippet",
            ),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="desktop_sticky_cta_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit site default"),
                    ("disabled", "Disabled"),
                    ("custom", "Custom snippet"),
                ],
                default="inherit",
                help_text="Control whether this page uses the site default or a custom CTA.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="desktop_sticky_cta_snippet",
            field=models.ForeignKey(
                blank=True,
                help_text="Used when mode is set to Custom snippet.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sum_core_navigation.desktopstickyctasnippet",
            ),
        ),
    ]
