# Generated by Django 5.2.10 on 2026-01-22 20:09

import sum_core.utils.links
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sum_core_pages", "0056_block_alt_text_standardization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepageherocta",
            name="url",
            field=models.CharField(
                help_text="URL or anchor (e.g., '/contact/' or '#contact').",
                max_length=255,
                validators=[sum_core.utils.links.validate_safe_link],
            ),
        ),
    ]
