# Generated by Django 5.2.10 on 2026-01-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sum_core_pages", "0057_add_url_validator_homepageherocta"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="seo_h1",
            field=models.CharField(
                blank=True,
                help_text="The main heading for SEO purposes (appears as small eyebrow text). Example: 'Expert Kitchen Fitters in Leeds'. If left blank, the page title is used. Keep it concise and keyword-rich.",
                max_length=120,
                verbose_name="SEO H1 Heading",
            ),
        ),
        migrations.AddField(
            model_name="blogpostpage",
            name="seo_h1",
            field=models.CharField(
                blank=True,
                help_text="The main heading for SEO purposes (appears as small eyebrow text). Example: 'Expert Kitchen Fitters in Leeds'. If left blank, the page title is used. Keep it concise and keyword-rich.",
                max_length=120,
                verbose_name="SEO H1 Heading",
            ),
        ),
        migrations.AddField(
            model_name="casestudypage",
            name="seo_h1",
            field=models.CharField(
                blank=True,
                help_text="The main heading for SEO purposes (appears as small eyebrow text). Example: 'Expert Kitchen Fitters in Leeds'. If left blank, the page title is used. Keep it concise and keyword-rich.",
                max_length=120,
                verbose_name="SEO H1 Heading",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="seo_h1",
            field=models.CharField(
                blank=True,
                help_text="The main heading for SEO purposes (appears as small eyebrow text). Example: 'Expert Kitchen Fitters in Leeds'. If left blank, the page title is used. Keep it concise and keyword-rich.",
                max_length=120,
                verbose_name="SEO H1 Heading",
            ),
        ),
        migrations.AddField(
            model_name="legalpage",
            name="seo_h1",
            field=models.CharField(
                blank=True,
                help_text="The main heading for SEO purposes (appears as small eyebrow text). Example: 'Expert Kitchen Fitters in Leeds'. If left blank, the page title is used. Keep it concise and keyword-rich.",
                max_length=120,
                verbose_name="SEO H1 Heading",
            ),
        ),
        migrations.AddField(
            model_name="portfolioindexpage",
            name="seo_h1",
            field=models.CharField(
                blank=True,
                help_text="The main heading for SEO purposes (appears as small eyebrow text). Example: 'Expert Kitchen Fitters in Leeds'. If left blank, the page title is used. Keep it concise and keyword-rich.",
                max_length=120,
                verbose_name="SEO H1 Heading",
            ),
        ),
        migrations.AddField(
            model_name="serviceindexpage",
            name="seo_h1",
            field=models.CharField(
                blank=True,
                help_text="The main heading for SEO purposes (appears as small eyebrow text). Example: 'Expert Kitchen Fitters in Leeds'. If left blank, the page title is used. Keep it concise and keyword-rich.",
                max_length=120,
                verbose_name="SEO H1 Heading",
            ),
        ),
        migrations.AddField(
            model_name="servicepage",
            name="seo_h1",
            field=models.CharField(
                blank=True,
                help_text="The main heading for SEO purposes (appears as small eyebrow text). Example: 'Expert Kitchen Fitters in Leeds'. If left blank, the page title is used. Keep it concise and keyword-rich.",
                max_length=120,
                verbose_name="SEO H1 Heading",
            ),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="seo_h1",
            field=models.CharField(
                blank=True,
                help_text="The main heading for SEO purposes (appears as small eyebrow text). Example: 'Expert Kitchen Fitters in Leeds'. If left blank, the page title is used. Keep it concise and keyword-rich.",
                max_length=120,
                verbose_name="SEO H1 Heading",
            ),
        ),
    ]
