# Generated by Django 5.2.10 on 2026-02-26 09:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sum_core_pages",
            "0063_alter_blogpostpage_body_alter_casestudypage_body_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("lead_paragraph", 1),
                    ("longform_article", 8),
                    ("article_section", 17),
                    ("content", 19),
                    ("numbered_steps", 24),
                    ("quote", 28),
                    ("social_proof_quote", 31),
                    ("image_block", 36),
                    ("call_to_action", 55),
                    ("spacer", 57),
                    ("divider", 59),
                    ("dynamic_form", 64),
                    ("rich_text", 65),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Lead paragraph copy. Use italics to highlight opening phrases.",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 0)]],
                        {"group": "Blog"},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                            ],
                            "help_text": "Preferred for long-form blog writing. Use H2/H3 headings to build the table of contents.",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Heading text to match (case-insensitive).",
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "help_text": "Stable anchor ID for this heading (lowercase letters, numbers, and hyphens only).",
                            "regex": "^[a-z][a-z0-9-]*$",
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 1,
                            "help_text": "Heading occurrence to target when the same heading repeats.",
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 3), ("anchor", 4), ("occurrence", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.ListBlock",
                        (6,),
                        {
                            "help_text": "Optional stable anchors for specific headings to prevent URL changes when heading copy is edited.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 2), ("anchor_overrides", 7)]],
                        {"group": "Blog"},
                    ),
                    9: (
                        "wagtail.blocks.RegexBlock",
                        (),
                        {
                            "help_text": "Optional anchor ID used for in-page links (lowercase letters, numbers, and hyphens only).",
                            "regex": "^[a-z][a-z0-9-]*$",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center")],
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional eyebrow label.", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["italic", "bold"],
                            "help_text": "Section heading. Use italics for accent styling.",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional subheading line under the main heading.",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional second subheading line.",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Style the first paragraph with a drop cap.",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                            ],
                            "required": True,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor", 9),
                                ("align", 10),
                                ("eyebrow", 11),
                                ("heading", 12),
                                ("subheading", 13),
                                ("subheading_secondary", 14),
                                ("drop_cap", 15),
                                ("body", 16),
                            ]
                        ],
                        {"group": "Blog"},
                    ),
                    18: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                            ],
                            "required": True,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("align", 10), ("body", 18)]],
                        {"group": "Blog"},
                    ),
                    20: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    21: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 20), ("description", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {"max_num": 8, "min_num": 1},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("steps", 23)]],
                        {"group": "Blog"},
                    ),
                    25: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Short editorial quote (1-3 sentences).",
                            "label": "Quote Text",
                        },
                    ),
                    26: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Role/description, e.g. Property Owner",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 25), ("author", 26), ("role", 27)]],
                        {"group": "Blog"},
                    ),
                    29: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Editorial quote (1-3 sentences).",
                            "label": "Quote Text",
                        },
                    ),
                    30: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional company logo.", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 29),
                                ("logo", 30),
                                ("author", 26),
                                ("role", 26),
                                ("company", 26),
                            ]
                        ],
                        {"group": "Blog"},
                    ),
                    32: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Short caption under the image.",
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Stretch to full-width container.",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 32),
                                ("alt_text", 33),
                                ("caption", 34),
                                ("full_width", 35),
                            ]
                        ],
                        {"group": "Blog"},
                    ),
                    37: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["italic", "bold"],
                            "help_text": "CTA heading. Use italics for accent styling.",
                            "required": True,
                        },
                    ),
                    38: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Supporting CTA copy.",
                            "required": True,
                        },
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("light", "Light"),
                                ("dark", "Dark"),
                                ("muted", "Muted"),
                            ],
                            "help_text": "Visual tone for the section background and text treatment.",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("compact", "Compact"),
                                ("regular", "Regular"),
                                ("spacious", "Spacious"),
                            ],
                            "help_text": "Vertical spacing density for the section.",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "CTA label text.",
                            "max_length": 80,
                            "required": True,
                        },
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("url", "External URL"),
                                ("path", "Internal path"),
                                ("email", "Email"),
                                ("phone", "Phone"),
                                ("anchor", "Anchor"),
                            ],
                            "help_text": "Select the type of link.",
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select an internal page.", "required": False},
                    ),
                    44: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter an external URL (include https://).",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter an internal path starting with / (e.g., /portfolio/?type=bootroom).",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    46: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Enter an email address.", "required": False},
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter a phone number (e.g., +44 20 7946 0958).",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter an anchor ID (e.g., 'contact' or '#contact').",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Custom display text for the link (optional).",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": None,
                            "help_text": "Force link to open in new tab. External URLs open in new tab by default.",
                            "required": False,
                        },
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 42),
                                ("page", 43),
                                ("url", 44),
                                ("path", 45),
                                ("email", 46),
                                ("phone", 47),
                                ("anchor", 48),
                                ("link_text", 49),
                                ("open_in_new_tab", 50),
                            ]
                        ],
                        {"help_text": "CTA destination.", "required": True},
                    ),
                    52: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                            ],
                            "help_text": "Optional CTA style.",
                            "required": False,
                        },
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 41), ("link", 51), ("style", 52)]],
                        {},
                    ),
                    54: (
                        "wagtail.blocks.ListBlock",
                        (53,),
                        {"max_num": 2, "min_num": 1},
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("eyebrow", 11),
                                ("heading", 37),
                                ("body", 38),
                                ("tone", 39),
                                ("density", 40),
                                ("buttons", 54),
                            ]
                        ],
                        {"group": "Blog"},
                    ),
                    56: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small (24px)"),
                                ("medium", "Medium (40px)"),
                                ("large", "Large (64px)"),
                                ("xlarge", "X-Large (96px)"),
                            ]
                        },
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("size", 56)]],
                        {"group": "Blog"},
                    ),
                    58: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("muted", "Muted"),
                                ("strong", "Strong"),
                                ("accent", "Accent"),
                            ]
                        },
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("style", 58)]],
                        {"group": "Blog"},
                    ),
                    60: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("sum_core_forms.FormDefinition",),
                        {"help_text": "Select the form to display", "required": True},
                    ),
                    61: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("inline", "Inline (renders in page flow)"),
                                ("modal", "Modal (button opens overlay)"),
                                ("sidebar", "Sidebar (fixed slide-in)"),
                            ],
                            "help_text": "How the form should be presented",
                        },
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Override default CTA button text (for modal/sidebar styles)",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 42),
                                ("page", 43),
                                ("url", 44),
                                ("path", 45),
                                ("email", 46),
                                ("phone", 47),
                                ("anchor", 48),
                                ("link_text", 49),
                                ("open_in_new_tab", 50),
                            ]
                        ],
                        {
                            "help_text": "Optional redirect after submission (use 'page' or 'path' for internal links)",
                            "required": False,
                        },
                    ),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("form_definition", 60),
                                ("presentation_style", 61),
                                ("cta_button_text", 62),
                                ("success_redirect", 63),
                            ]
                        ],
                        {"group": "Forms"},
                    ),
                    65: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                            ],
                            "help_text": "Add formatted text content. Use H2-H4 for headings, avoid H1.",
                            "label": "Rich Text",
                            "required": False,
                        },
                    ),
                },
                help_text="Article content with optional form CTAs",
            ),
        ),
    ]
