# Generated by Django 5.2.10 on 2026-01-23 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentGap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gap_type",
                    models.CharField(
                        choices=[
                            ("missing_page", "Missing Page"),
                            ("missing_schema", "Missing Schema"),
                            ("thin_content", "Thin Content"),
                        ],
                        help_text="Type of content gap detected.",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title describing the gap.", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description and recommendation."
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0, help_text="Confidence score (0.0-1.0)."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this gap was detected."
                    ),
                ),
                (
                    "dismissed",
                    models.BooleanField(
                        default=False, help_text="Whether this gap has been dismissed."
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        help_text="The site this gap belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_gaps",
                        to="wagtailcore.site",
                    ),
                ),
                (
                    "source_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional source page (for page-level gaps).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_gaps",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Gap",
                "verbose_name_plural": "Content Gaps",
                "ordering": ["-confidence_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PageSEOAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_data",
                    models.JSONField(
                        default=dict,
                        help_text="Analysis results (issues, metrics, etc.).",
                    ),
                ),
                (
                    "health_score",
                    models.PositiveIntegerField(
                        default=0, help_text="SEO health score (0-100)."
                    ),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this analysis was last updated."
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Cache invalidation version."
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="The page this analysis belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_analysis",
                        to="wagtailcore.page",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Page SEO Analysis",
                "verbose_name_plural": "Page SEO Analyses",
            },
        ),
        migrations.CreateModel(
            name="InternalLinkSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anchor_text",
                    models.CharField(
                        help_text="Suggested anchor text for the link.", max_length=200
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(
                        default=0.0, help_text="Relevance score (0.0-1.0)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        help_text="Current status of this suggestion.",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this suggestion was created."
                    ),
                ),
                (
                    "source_page",
                    models.ForeignKey(
                        help_text="The page where the link should be added.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_link_suggestions",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "target_page",
                    models.ForeignKey(
                        help_text="The page being suggested as link target.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_link_suggestions",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal Link Suggestion",
                "verbose_name_plural": "Internal Link Suggestions",
                "ordering": ["-relevance_score", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_page", "target_page"),
                        name="unique_source_target_link_suggestion",
                    )
                ],
            },
        ),
    ]
