# Generated by Django 5.2.10 on 2026-01-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo_engine", "0002_serviceareaconfig_locationpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationpage",
            name="seo_h1",
            field=models.CharField(
                blank=True,
                help_text="The main heading for SEO purposes (appears as small eyebrow text). Example: 'Expert Kitchen Fitters in Leeds'. If left blank, the page title is used. Keep it concise and keyword-rich.",
                max_length=120,
                verbose_name="SEO H1 Heading",
            ),
        ),
    ]
