# Generated by Django 5.2.10 on 2026-01-25 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo_engine", "0003_add_seo_h1_field"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageseoanalysis",
            name="page",
            field=models.OneToOneField(
                help_text="The page this analysis belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seo_analysis",
                to="wagtailcore.page",
            ),
        ),
    ]
