# Generated by Django 5.2.10 on 2026-01-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seo_engine", "0004_alter_locationpage_body"),
        ("seo_engine", "0004_alter_pageseoanalysis_page"),
    ]

    operations = []
