# Generated by Django 5.2.9 on 2026-01-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_homepage_seo_nofollow_homepage_seo_noindex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Optional. Overrides the search description for SEO snippets (recommended max 160 characters).",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Optional. Overrides the SEO title when set; otherwise uses the SEO title or “{page title} | {site name}”.",
                max_length=60,
            ),
        ),
    ]
