# Generated by Django 5.1.15 on 2026-01-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_homepage_meta_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="desktop_sticky_cta_mode",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit site default"),
                    ("disabled", "Disabled"),
                    ("custom", "Custom snippet"),
                ],
                default="inherit",
                help_text="Control whether this page uses the site default or a custom CTA.",
                max_length=20,
            ),
        ),
    ]
