# Generated by Django 5.1.15 on 2026-01-19 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_homepage_desktop_sticky_cta_mode"),
        (
            "sum_core_navigation",
            "0006_headernavigation_desktop_sticky_cta_enabled_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="desktop_sticky_cta_snippet",
            field=models.ForeignKey(
                blank=True,
                help_text="Used when mode is set to Custom snippet.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sum_core_navigation.desktopstickyctasnippet",
            ),
        ),
    ]
